steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - mc_sync
  - --region=asia-south1
  - --source=.
  - --trigger-http
  - --runtime=python38
  - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY