# -*- coding: utf-8 -*-
"""nse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/manishrawat2022/ReStock/blob/main/nse.ipynb

#### Installations
"""
"""#### Imports"""

import pymongo
from pymongo import MongoClient
from nsetools import Nse
from nsepy import get_history
import datetime
from datetime import date

"""#### Initialize NSE Tools"""

nse = Nse()

"""#### Get Stock and indexes codes"""

def sync_nse_data():

  indexes = nse.get_index_list()

  stocks = nse.get_stock_codes()

  #We will collect data from 2017 to today
  start_date = date(2017,1,1)
  end_date = date.today()

  """#### Create MongoDB client"""

  client = MongoClient('mongodb+srv://random:Random@stock.mbex3cy.mongodb.net/?retryWrites=true&w=majority')
  db = client["Stocks"]
  collection = db["stock_history"]

  """#### Put stock data in MongoDB"""

  count = 0
  for stock in stocks:
    iterator = collection.find({"Symbol":stock}).sort("Date", pymongo.DESCENDING).limit(1)
    st_date = next(iterator, None)
    if st_date:
      st_date = st_date["Date"].date()+ datetime.timedelta(days=1)
    else:
      st_date = start_date

    documents = []
    history = get_history(symbol=stock,
                    start=st_date,
                    end=end_date)
    history = history.reset_index()

    for row in history.iterrows():
      document = dict([(column, row[1][column])for column in history.columns])
      document["Date"] = datetime.datetime.combine(document["Date"], datetime.datetime.min.time())
      documents.append(document)
    
    if documents:
      count += len(documents)
      collection.insert_many(documents, ordered=False)

  print(f"Pushed {count} document for stocks")
  """#### Put index data in MongoDB"""

  collection = db["index_history"]

  count = 0
  for index in indexes:
    iterator = collection.find({"Name":index}).sort("Date", pymongo.DESCENDING).limit(1)
    st_date = next(iterator, None)
    if st_date:
      st_date = st_date["Date"].date()+ datetime.timedelta(days=1)
    else:
      st_date = start_date

    documents = []
    history = get_history(symbol=index,
                    start=st_date,
                    end=end_date,
                    index=True)
    history = history.reset_index()

    for row in history.iterrows():
      document = dict([(column, row[1][column])for column in history.columns])
      document["Name"] = index
      document["Date"] = datetime.datetime.combine(document["Date"], datetime.datetime.min.time())
      documents.append(document)
    
    if documents:
      count+=len(documents)
      collection.insert_many(documents, ordered=False)

  print(f"Pushed {count} document for indexes")
